# Generated by Django 4.1.13 on 2025-05-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appproducto_authgroup_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elproducto',
            old_name='iidproducto',
            new_name='idprod',
        ),
    ]
