# Generated by Django 4.1.13 on 2025-05-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_iidproducto_elproducto_idprod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elproducto',
            name='idprod',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
